name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Continuous Integration - Test
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.6,name=iPhone 11 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get Dependencies
        run: pod install

      - name: Create GitVersion.swift
        run: |
          ./scripts/create-git-version-swift-file.sh

      - name: Build
        run: |
          xcodebuild clean build -workspace Introspective.xcworkspace -scheme CI-CD -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}

      - name: Test
        run: |
          xcodebuild test -workspace Introspective.xcworkspace -scheme CI-CD -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
